/**
 * The blocks.
 *
 * The PHPUnit suite already proves the render callbacks return the same markup
 * the shortcodes return, so repeating that here would buy nothing. What only a
 * browser can answer is whether the *built* JavaScript works: `build/` is
 * generated by bin/build and is not in the repository, so every assertion below
 * is also an assertion that the build ran and produced something a browser can
 * load.
 *
 * Three things are worth a browser, and nothing else here is:
 *
 * * the editor script loads and registers both blocks -- a broken build, a
 *   missing dependency in index.asset.php or a bad block.json all show up here
 *   and nowhere else;
 * * a poll rendered from a block can actually be voted in, which exercises the
 *   front-end script against markup that arrived by a different route;
 * * the shortcode still renders on the front end, because that is the promise
 *   the whole design rests on and it is worth checking where a reader can see
 *   it rather than only in a unit test.
 */

const { test, expect } = require( '@wordpress/e2e-test-utils-playwright' );
const {
	createPoll,
	expectResults,
	poll,
	uniqueQuestion,
	vote,
} = require( './helpers.js' );

/** The two blocks this plugin registers. */
const POLL_BLOCK = 'wp-polls/poll';
const ARCHIVE_BLOCK = 'wp-polls/page-polls';

test.describe( 'The blocks', () => {
	let pollId;

	test.beforeEach( async () => {
		pollId = createPoll( {
			question: uniqueQuestion( 'Block poll' ),
			answers: [ 'Yes', 'No' ],
		} );
	} );

	test.describe( 'in the editor', () => {
		test( 'both blocks are registered, under the prefixed name', async ( {
			admin,
			editor,
			page,
		} ) => {
			await admin.createNewPost();
			await editor.canvas.locator( 'body' ).waitFor();

			const names = await page.evaluate( () =>
				window.wp.blocks.getBlockTypes().map( ( type ) => type.name ),
			);

			// If the build did not run, or index.asset.php named a dependency
			// that does not exist, the editor script never executes and neither
			// name is here -- which is the failure this whole file exists for.
			expect( names ).toContain( POLL_BLOCK );
			expect( names ).toContain( ARCHIVE_BLOCK );

			// The prefix is not decoration: a block name is written into
			// post_content and lives there for the life of the post.
			expect( names ).not.toContain( 'polls/poll' );
		} );

		test( 'the poll block previews the poll it is given', async ( {
			admin,
			editor,
		} ) => {
			await admin.createNewPost();
			await editor.insertBlock( {
				name: POLL_BLOCK,
				attributes: { id: pollId },
			} );

			// The preview is core's ServerSideRender, which posts the attributes
			// to /wp/v2/block-renderer/ and draws what the front end would draw.
			// Seeing the poll here is what proves the block earns no REST route
			// of its own.
			await expect(
				editor.canvas.locator( `#polls-${ pollId }` ),
			).toBeVisible();

			// "Loading ..." is the AJAX placeholder, and it is hidden by a
			// stylesheet rule rather than by an attribute -- so an editor that
			// does not enqueue the front-end stylesheet shows it permanently
			// under every poll. It did, until enqueue_block_assets was wired
			// up, and a screenshot was the only thing that noticed.
			await expect(
				editor.canvas.locator( `#polls-${ pollId }-loading` ),
			).toBeHidden();
		} );
	} );

	test.describe( 'on the front end', () => {
		test( 'a post holding the block renders the poll', async ( {
			page,
			requestUtils,
		} ) => {
			const post = await requestUtils.createPost( {
				title: 'A poll in a block',
				content: `<!-- wp:${ POLL_BLOCK } {"id":${ pollId }} /-->`,
				status: 'publish',
			} );

			await page.goto( post.link );

			await expect( poll( page, pollId ) ).toBeVisible();
		} );

		test( 'a poll rendered from a block can be voted in', async ( {
			page,
			requestUtils,
		} ) => {
			const post = await requestUtils.createPost( {
				title: 'Voting from a block',
				content: `<!-- wp:${ POLL_BLOCK } {"id":${ pollId }} /-->`,
				status: 'publish',
			} );

			await page.goto( post.link );
			await vote( page, pollId );

			// The front-end script is enqueued on every page rather than when a
			// poll is detected, so this is not testing the enqueue -- it is
			// testing that markup which arrived through the block carries the
			// nonce and the data attributes the script needs.
			await expectResults( page, pollId );
		} );

		test( 'the block and the shortcode render the same poll', async ( {
			page,
			requestUtils,
		} ) => {
			const post = await requestUtils.createPost( {
				title: 'Both entry points at once',
				content: `<!-- wp:${ POLL_BLOCK } {"id":${ pollId }} /-->\n\n[poll id="${ pollId }"]`,
				status: 'publish',
			} );

			await page.goto( post.link );

			// Same id, so both renders produce the same container -- which is
			// the point: two entry points, one renderer. Two is what proves the
			// shortcode still works with a block on the same page.
			await expect( poll( page, pollId ) ).toHaveCount( 2 );
		} );

		test( 'the archive block renders the archive', async ( {
			page,
			requestUtils,
		} ) => {
			const post = await requestUtils.createPost( {
				title: 'An archive in a block',
				content: `<!-- wp:${ ARCHIVE_BLOCK } /-->`,
				status: 'publish',
			} );

			await page.goto( post.link );

			await expect( page.locator( '.wp-polls-archive' ) ).toBeVisible();
		} );
	} );
} );
